#!/bin/bash
#                                           .:oydNMMMMMMMMMMMMMMMMMMMMMMMMNmyo/.
#                                      `-+hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho:`
#                                   .+yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+-
#                                .+dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo-
#                              :hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd/`
#                           `+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo.
#                         `+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.
#                        /mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo`
#                      -hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/
#                      /o+oooooossyyhddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy`
#                                    ```.-:+sydmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdNMMMMMMMMMMMMMMMMMMMMd-
#                                             `.-/sdNMMMMMMMMMMMMMMMMMMMMMNmyyNM/.omMMMMMMMMMMMMMMMMMMMN:
#                                                  `.:sdNMMMMMMMMMMhhhys+:.`  -/-  .+dMMMMMMMMMMMMMMMMMMN/
#                .y/                                   `-+hNMMMMMmo                  `:ymNNMMMMMMMMMMMMMMN/
#               `dMMh-                                     -odNMd.                      `.-mMMMMMMMMMMMMMMN-
#               yMMMMN+                                      `:y:                       `.`-sdNMMMMMMMMMMMMm`
#              :MMMMMMMo                                                                `sh.  /MMMMMMMMMMMMMs
#             `mMMMMMMMM/                                                                `--   +NMMMMMMMMMMMN.
#             /MMMMMMMMMm                                                 `+o-                  :hNMMMMMMMMMMy
#             hMMMMMMMMMN                                                .mMMd---.`               :ymMMMMMMMMN`
#            `MMMMMMMMMMmyhhhs/`                                         /MMMMMMMNh/                `/hNMMMMMM:
#            :MMMMMMMMMMMMMMMMMm+                                        `hMMMMMMMMMy.   :o/`  ``      :NMMMMMs
#            +MMMMMMMMMMMMMMMMMMMs                                         /+sMMMMMMMm-  +mMm/`sdyyssh.-NMMMMMh
#            oMMMMMMMMMMMMMMMMMMMM:                                           oNMMMMMMN- `yMMMd+yNMMMMhNMMMMMMh
#            oMMMMMMMMMMMMMMMMMMMMy                                            .sNMMMMMm` `+NMMMNmMMMMMMMMMMMMh
#            +MMMMMMMMMMMMMMMMMMMMo                                              `/yNMMMy`  sMMMMMMMMMMMMMMMMMy
#            -MMMMMMMMMMMMMMMMMMMN.                                                 `+dMMms+dMMMMMMMMMMMMMMMMM+
#            `NMMMMMMMMMMMMMMMMMMo+yhddhy.                                             :mMMMMMMMMMMMMMMMMMMMMM-
#             yMMMMMMMMMMMMMMMMMMMMMMMMMMy                                              `mMMMMMMMMMMMMMMMMMMMm
#             -MMMMMMMMMMMMMMMMMMMMMMMMMMd                                               /MMMMMMMMMMMMMMMMMMM+
#              hMMMMMMMMMMMMMMMMMMMMMMMMMy                                               `mMMMMMMMMMMMMMMMMMm`
#              .NMMMMMMMMMMMMMMMMMMMMMMMMyyy-                                             `yMMMMMMMMMMMMMMMM:
#               /MMMMMMMMMMMMMMMMMMMMMMMMMMMh                                             +yMMMMMMMMMMMMMMMs
#                sMMMMMMMMMMMMMMMMMMMMMMMMMMm                                             .mMMMMMMMMMMMMMMd`
#                 yMMMMMMMMMMMMMMMMMMMMMMMMMd+yo`                                          sMMMMMMMMMMMMMd`
#                 `yMMMMMMMMMMMMMMMMMMMMMMMMMMMd`                                          mMMMMMMMMMMMMd`
#                   oMMMMMMMMMMMMMMMMMMMMMMNh+-`                                          /MMMMMMMMMMMMy`
#                    /NMMMMMMMMMMMMMMMMMNh/`                                          .oyyhMMMMMMMMMMNo
#                     .hMMMMMMMMMMMMMMNy-                                          ./yNMMMMMMMMMMMMMd-
#                      `/mMMMMMMMMMMMh-                                           :NMMMMMMMMMMMMMMNo`
#                        .oNMMMMMMMN+`                                       `:oo+dMMMMMMMMMMMMMNy.
#                          .smMMMMd-                                      ./ymMMMMMMMMMMMMMMMMNy-
#                            .odMy`                                       -mMMMMMMMMMMMMMMMMms-
#                              `-`                             `.:+hh:     -mMMMMMMMMMMMMNh/.
#                                                      ``.-:+shdNMMMMNs.    .hMMMMMMMMmh+-
#                                                     +yhdmmmmmmmmmmmmmh:    `+osydds:.
#                                                     `.................`
#
#
#                                      D R A G O N H A C K          L J U B L J A N A
#
#                                                       2   0   1   5
# Author: Tamius Han (xternal7)
#
#
#
#         Ker na prvi pogled prvih 90 vrstic zgleda kot increase_ach:          r e s e t _ a c h
# Because first 90 something lines look very similar to increase_ach:
#
#                                                :::
#
# Vsi argumenti so ime dosežka. Če je bil dosežek, ki ga hočemo ponastaviti, že dosežen, potem ne naredimo
# ničesar.
#
# Da, naenkrat se lahko ponastavi več dosežkov
#
#
# All arguments are achievent names. If we already achieved the achievement we're about to reset,
# we do nothing and leave it as it is.
#
# Yes, you can reset multiple achievements at once.
#
#                                                :::
#
# Format datoteke: achievements
# Formatting in the file: achievements
#
#   argnum :   0          1              2         3         4         5           6         7               8
#      ime :   #      ime_dosezka     dosezen   napredek   cilj      slika       zvok      opis       opis za/desc for
#     name :   #      achievement     achieved  progress  target      icon       sound  description  print-achievements
#            ==========================================================================================================
# tip/type :  int       string          1/0       int       int      string     string    string          string
#
#
#
#    string ne sme vsebovati presledkov | string shouldn't contain whitespaces
#      namesto njih uporabite podčrtaj  |       use underscore instead
#
#
# POT DO DATOTEKE / PATH TO achievements:
afile=~/.config/punishell/achievements

while [ $# -gt 0 ] ; do
  ach_grep="$(cat "$afile" | grep -i " $1 ")"

  IFS=' ' read -a ach_linearr <<< "$ach_grep"
  if [[ ${ach_linearr[2]} -eq 0 ]] ; then
    ach_linearr[3]=0  
    rep="${ach_linearr[@]}"
    sed -i 's|'"$ach_grep"'|'"$rep"'|' "$afile"
  fi
  shift 1
done